version: '3'
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: [mysqld, --default-authentication-plugin=mysql_native_password, --lower_case_table_names=1]
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db


