version: '3'
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST='%'
    command: [mysqld, --default-authentication-plugin=mysql_native_password, --lower_case_table_names=1]
    volumes:
      - ./data:/var/lib/mysql
      - ./populate-data:/populate-data
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  nodejs:
    depends_on:
      - db
    build: ""
    volumes:
      - ./keys:/keys
    ports:
      - 4941:4941
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=pisspricer
      - MYSQL_PORT=3306
      - OPEN_PORT=4941
      - IMAGE_BUCKET
      - BUCKET_KEY_PATH
      - EMAIL_HOST
      - EMAIL_USER
      - EMAIL_PASSWORD
      - EMAIL_ADDRESS
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4941/api/v1/brands" ]
      timeout: 10s
      retries: 10
