name: API

on:
  push:
    branches:
      - master
    paths:
      - api/**

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: TooMuch4U/runner-post-cleanup@v1
      - uses: actions/checkout@master
      - uses: actions/setup-node@master

      - name: Create env file
        working-directory: api
        run: |
          touch .env
          echo IMAGE_BUCKET=${{ secrets.API_IMAGE_BUCKET }} >> .env
          echo BUCKET_KEY_PATH=/keys/gcloud.json >> .env
          cat .env

      - name: Create google cloud key file
        working-directory: api
        run: |
          mkdir keys
          touch keys/gcloud.json
          echo ${{ secrets.API_GCLOUD_KEY_CONTENTS }} >> keys/gcloud.json

      - name: Copy files
        working-directory: api
        run: |
          cp -r src /containers/api/
          cp .env /containers/api/
          cp docker-compose.yml /containers/api/
          cp Dockerfile /containers/api/
          cp .dockerignore /containers/api/
          cp -r keys/* /containers/api/keys

      - name: docker-compose up
        working-directory: /containers/api
        run: |
          docker-compose build
          docker-compose up -d
