name: Frontend Build Check

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!staging'
    paths:
      - frontend/**

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        working-directory: frontend
        run: npm install
      - name: Building the project
        working-directory: frontend
        run: npm run build