name: Frontend

on:
  push:
    paths:
      - frontend/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        working-directory: frontend
        run: npm install
      - name: Building the project
        working-directory: frontend
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: frontend-dist
          path: frontend/dist

  deploy-prod:
    if: github.ref == 'refs/heads/master'
    needs: [ build ]
    runs-on: self-hosted
    steps:
      - name: Clean working directory
        shell: bash
        run: |
          cd $RUNNER_WORKSPACE
          cd ..
          rm -r *
      - name: Download built frontend
        uses: actions/download-artifact@v2
        with:
          name: frontend-dist
      - name: Remove old site
        run: rm -r /var/www/main/*
      - name: Copy new site
        working-directory: frontend
        run: cp -r * /var/www/main

  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    needs: [ build ]
    runs-on: self-hosted
    steps:
      - uses: TooMuch4U/runner-post-cleanup@master
      - name: Download built frontend
        uses: actions/download-artifact@v2
        with:
          name: frontend-dist
      - name: Remove old site
        run: rm -r /var/www/dev/*
      - name: Copy new site
        run: cp -r * /var/www/dev
