name: Frontend Deploy Prod

on:
  push:
    branches:
      - master
    paths:
      - frontend/**

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        working-directory: frontend
        run: npm install
      - name: Building the project
        working-directory: frontend
        run: npm run build
  deploy:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [ build-check ]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        working-directory: frontend
        run: npm install
      - name: Building the project
        working-directory: frontend
        run: npm run build
      - name: Remove old site
        run: rm -r /var/www/main
      - name: Copy new site
        working-directory: frontend
        run: cp -r ./dist/* /var/www/main
